AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: CodeSensei Backend - Health Check Skeleton

Globals:
  Function:
    Runtime: nodejs22.x
    Timeout: 30
    MemorySize: 128
    Environment:
      Variables:
        NODE_ENV: !Ref Environment
        REGION: !Ref AWS::Region
        USERS_TABLE: !Ref UsersTable
        SESSIONS_TABLE: !Ref SessionsTable
        THREADS_TABLE: !Ref ThreadsTable
        MESSAGES_TABLE: !Ref MessagesTable
        RATE_LIMITS_TABLE: !Ref RateLimitsTable
        AUTH_RATE_LIMIT_PER_MINUTE: "5"
        CORS_ALLOWED_ORIGIN: !Ref CorsAllowedOrigin
        JWT_ACCESS_EXPIRY: "15m"
        JWT_REFRESH_EXPIRY: "7d"
        JWT_ISSUER: CodeSensei
        ACCESS_COOKIE_NAME: accessToken
        REFRESH_COOKIE_NAME: refreshToken
        JWT_SECRET: !Sub "{{resolve:secretsmanager:CodeSensei-JWT-Secret-${Environment}:SecretString:secret}}"

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name
  CorsAllowedOrigin:
    Type: String
    Default: https://main.dnq80x6al42k7.amplifyapp.com
    Description: Allowed CORS origin for API Gateway responses

Resources:
  CodeSenseiApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "CodeSensei-API-${Environment}"
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,PUT,PATCH,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization,X-Requested-With,Cookie'"
        AllowOrigin: !Sub "'${CorsAllowedOrigin}'"
        AllowCredentials: true
      Auth:
        DefaultAuthorizer: NONE

  HealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "CodeSensei-HealthCheck-${Environment}"
      CodeUri: src/health/
      Handler: index.handler
      Description: Health check endpoint for CodeSensei
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ThreadsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable
      Events:
        HealthCheckApi:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /health
            Method: GET
        HealthCheckOptionsApi:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /health
            Method: OPTIONS

  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "CodeSensei-Auth-${Environment}"
      CodeUri: src/auth/
      Handler: index.handler
      Description: Authentication endpoints for CodeSensei
      MemorySize: 256
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref RateLimitsTable
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
              Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:CodeSensei-JWT-Secret-${Environment}-*"
      Events:
        Signup:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /auth/signup
            Method: POST
        Login:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /auth/login
            Method: POST
        Logout:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /auth/logout
            Method: POST
        Refresh:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /auth/refresh
            Method: POST
        AuthOptions:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /auth/{proxy+}
            Method: OPTIONS

  UsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "CodeSensei-Users-${Environment}"
      CodeUri: src/users/
      Handler: index.handler
      Description: User profile management endpoints for CodeSensei
      MemorySize: 256
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        GetProfile:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /users/me
            Method: GET
        UpdateProfile:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /users/me
            Method: PUT
        ChangePassword:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /users/me/password
            Method: PUT
        DeleteAccount:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /users/me
            Method: DELETE
        UsersOptionsSelf:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /users/me
            Method: OPTIONS
        UsersOptionsPassword:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /users/me/password
            Method: OPTIONS

  SessionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "CodeSensei-Sessions-${Environment}"
      CodeUri: src/sessions/
      Handler: index.handler
      Description: Session management endpoints for CodeSensei
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          SESSION_SAVE_RATE_LIMIT_PER_MINUTE: "60"
          SESSION_CREATE_RATE_LIMIT_PER_MINUTE: "20"
          MAX_SESSIONS_PER_USER: "100"
          MAX_SESSION_CODE_BYTES: "5242880"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref RateLimitsTable
      Events:
        ListSessions:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /sessions
            Method: GET
        CreateSession:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /sessions
            Method: POST
        SessionsOptionsRoot:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /sessions
            Method: OPTIONS
        GetSession:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /sessions/{id}
            Method: GET
        UpdateSession:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /sessions/{id}
            Method: PUT
        UpdateSessionMetadata:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /sessions/{id}/metadata
            Method: PATCH
        DeleteSession:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /sessions/{id}
            Method: DELETE
        SessionsOptionsItem:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /sessions/{id}
            Method: OPTIONS
        SessionsOptionsMetadata:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /sessions/{id}/metadata
            Method: OPTIONS

  ThreadsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "CodeSensei-Threads-${Environment}"
      CodeUri: src/threads/
      Handler: index.handler
      Description: Thread management endpoints for CodeSensei
      MemorySize: 256
      Timeout: 20
      Environment:
        Variables:
          MAX_THREADS_PER_SESSION: "50"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ThreadsTable
        - DynamoDBReadPolicy:
            TableName: !Ref SessionsTable
      Events:
        CreateThread:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /sessions/{id}/threads
            Method: POST
        ListThreads:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /sessions/{id}/threads
            Method: GET
        GetThread:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /threads/{thread_id}
            Method: GET
        UpdateThread:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /threads/{thread_id}
            Method: PUT
        DeleteThread:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /threads/{thread_id}
            Method: DELETE
        SessionsThreadsOptions:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /sessions/{id}/threads
            Method: OPTIONS
        ThreadsOptions:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /threads/{thread_id}
            Method: OPTIONS
        UpdateThreadAnchor:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /threads/{thread_id}/anchor
            Method: PATCH
        ThreadsAnchorOptions:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /threads/{thread_id}/anchor
            Method: OPTIONS
  MessagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "CodeSensei-Messages-${Environment}"
      CodeUri: src/messages/
      Handler: index.handler
      Description: Message management endpoints for CodeSensei
      MemorySize: 256
      Timeout: 20
      Environment:
        Variables:
          MAX_MESSAGES_PER_THREAD: "500"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable
        - DynamoDBReadPolicy:
            TableName: !Ref ThreadsTable
      Events:
        CreateMessage:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /threads/{thread_id}/messages
            Method: POST
        ListMessages:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /threads/{thread_id}/messages
            Method: GET
        MessagesOptions:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /threads/{thread_id}/messages
            Method: OPTIONS
  AIFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "CodeSensei-AI-${Environment}"
      CodeUri: src/ai/
      Handler: index.handler
      Description: AI analysis endpoint for CodeSensei
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          AI_RATE_LIMIT_PER_MINUTE: "10"
          BEDROCK_MODEL_ID: "anthropic.claude-3-sonnet-20240229-v1:0"
          BEDROCK_REGION: "us-east-1"
          BEDROCK_MAX_OUTPUT_TOKENS: "4000"
          BEDROCK_TEMPERATURE: "0.7"
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ThreadsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref RateLimitsTable
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource: !Sub "arn:aws:bedrock:${AWS::Region}::foundation-model/*"
      Events:
        Analyze:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /ai/analyze
            Method: POST
        AIOptions:
          Type: Api
          Properties:
            RestApiId: !Ref CodeSenseiApi
            Path: /ai/analyze
            Method: OPTIONS
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "CodeSensei-Users-${Environment}"
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: UsernameIndex
          KeySchema:
            - AttributeName: username
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  SessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "CodeSensei-Sessions-${Environment}"
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserIdIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  ThreadsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "CodeSensei-Threads-${Environment}"
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: thread_id
          AttributeType: S
        - AttributeName: session_id
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      KeySchema:
        - AttributeName: thread_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: SessionIdIndex
          KeySchema:
            - AttributeName: session_id
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "CodeSensei-Messages-${Environment}"
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: thread_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: thread_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE

  RateLimitsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "CodeSensei-RateLimits-${Environment}"
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      AttributeDefinitions:
        - AttributeName: rate_key
          AttributeType: S
      KeySchema:
        - AttributeName: rate_key
          KeyType: HASH

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${CodeSenseiApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/"
    Export:
      Name: !Sub "CodeSensei-ApiUrl-${Environment}"

  HealthCheckEndpoint:
    Description: Health check endpoint
    Value: !Sub "https://${CodeSenseiApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/health"

  HealthCheckFunctionArn:
    Description: Health check Lambda ARN
    Value: !GetAtt HealthCheckFunction.Arn
    Export:
      Name: !Sub "CodeSensei-HealthCheckFunction-${Environment}"

  AuthFunctionArn:
    Description: Auth Lambda function ARN
    Value: !GetAtt AuthFunction.Arn
    Export:
      Name: !Sub "CodeSensei-AuthFunction-${Environment}"

  UsersFunctionArn:
    Description: Users Lambda function ARN
    Value: !GetAtt UsersFunction.Arn
    Export:
      Name: !Sub "CodeSensei-UsersFunction-${Environment}"

  SessionsFunctionArn:
    Description: Sessions Lambda function ARN
    Value: !GetAtt SessionsFunction.Arn
    Export:
      Name: !Sub "CodeSensei-SessionsFunction-${Environment}"

  UsersTableName:
    Description: Users DynamoDB table name
    Value: !Ref UsersTable
    Export:
      Name: !Sub "CodeSensei-UsersTable-${Environment}"

  SessionsTableName:
    Description: Sessions DynamoDB table name
    Value: !Ref SessionsTable
    Export:
      Name: !Sub "CodeSensei-SessionsTable-${Environment}"

  ThreadsTableName:
    Description: Threads DynamoDB table name
    Value: !Ref ThreadsTable
    Export:
      Name: !Sub "CodeSensei-ThreadsTable-${Environment}"

  MessagesTableName:
    Description: Messages DynamoDB table name
    Value: !Ref MessagesTable
    Export:
      Name: !Sub "CodeSensei-MessagesTable-${Environment}"

  ThreadsFunctionArn:
    Description: Threads Lambda function ARN
    Value: !GetAtt ThreadsFunction.Arn
    Export:
      Name: !Sub "CodeSensei-ThreadsFunction-${Environment}"

  MessagesFunctionArn:
    Description: Messages Lambda function ARN
    Value: !GetAtt MessagesFunction.Arn
    Export:
      Name: !Sub "CodeSensei-MessagesFunction-${Environment}"

  RateLimitsTableName:
    Description: Rate limits DynamoDB table name
    Value: !Ref RateLimitsTable
  AIFunctionArn:
    Description: AI Lambda function ARN
    Value: !GetAtt AIFunction.Arn
    Export:
      Name: !Sub "CodeSensei-AIFunction-${Environment}"
